Dev
golang-tech-leaders/recycling pull request #12
Opened 2020-11-26 20:51 UTC by khdaniel

Добавил DEV-пайаплайн сборки. Учёл замечания по предыдущему пул-реквесту, экспериментально подключил контексты.

2020-11-29 08:57 UTC, ilyakaznacheev requested changes
В целом хорошо, убрать ненужные deferred функции и желательно перенести перевод интов во время в структуру, чтобы не делать это при каждом вызове (в реальности за таймаутами следит `http.Server`, поэтому руками эти таймауты делать не нужно, достаточно почитать документацию по таймаутам в http и настроить их в `http.Server`.

Также желательно включить в IDE автоматическую подстановку перевода строки в конце файла - в unix строка считается по переводу строки в конце, если его нет, то последняя строчка может где-то считаться некорректно.

2020-11-29 08:57 UTC, ilyakaznacheev commented on internal/config/config.go
> +func getConfigFile() string {
Здесь неверное название функции - функция возвращает не файл, а путь к файлу.

Логично ее назвать как-то вроде `getConfigFilePath`

2020-11-29 08:57 UTC, ilyakaznacheev commented on internal/platform/server/handlers.go
> +	ctx, cancel := context.WithTimeout(r.Context(), time.Duration(s.timeout)*time.Second)
В этом случае `s.timeout` должен иметь тип не int, а `time.Duration`, а умножаться на секунды при заполнени структуры.

В целом этого можно не делать, потому что в `http.Server` есть таймауты, по которым контекст запроса будет закрываться.

2020-11-29 08:57 UTC, ilyakaznacheev commented on internal/platform/server/handlers.go
> +	}()
Нет необходимости делать это при завершении функции. Если функция завершилась, значит действия, к которым может применяться таймаут, уже выполнились.

В этом случае `cancel` можно просто не использовать:

```go
ctx, _ := context.WithTimeout(...)
```

2020-11-29 08:57 UTC, ilyakaznacheev commented on internal/platform/server/handlers.go
> +	}()
Аналогично

2020-11-30 12:58 UTC, khdaniel commented on internal/platform/server/handlers.go
> +	}()
Изначально так и делал, но потом VSCode стал этой дело подсвечивать и я пошёл читать исходники. Дошёл вот до такого:

2020-11-30 13:01 UTC, khdaniel commented on internal/platform/server/handlers.go
> +	}()
И вот коммент от vscode:
```go
the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```

2020-12-01 17:56 UTC, ilyakaznacheev approved these changes

2020-12-01 17:56 UTC, merged